2023/04/11 05:55:52 [emerg] 1#1: cannot load certificate "/etc/letsencrypt/live/auctionforfun.site/certificate.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/auctionforfun.site/certificate.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2023/04/11 05:55:53 [emerg] 1#1: cannot load certificate "/etc/letsencrypt/live/auctionforfun.site/certificate.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/auctionforfun.site/certificate.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2023/04/11 05:55:55 [emerg] 1#1: cannot load certificate "/etc/letsencrypt/live/auctionforfun.site/certificate.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/auctionforfun.site/certificate.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2023/04/11 05:55:57 [emerg] 1#1: cannot load certificate "/etc/letsencrypt/live/auctionforfun.site/certificate.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/auctionforfun.site/certificate.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2023/04/11 05:55:58 [emerg] 1#1: cannot load certificate "/etc/letsencrypt/live/auctionforfun.site/certificate.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/auctionforfun.site/certificate.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2023/04/11 05:56:01 [emerg] 1#1: cannot load certificate "/etc/letsencrypt/live/auctionforfun.site/certificate.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/auctionforfun.site/certificate.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2023/04/11 05:56:05 [emerg] 1#1: cannot load certificate "/etc/letsencrypt/live/auctionforfun.site/certificate.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/auctionforfun.site/certificate.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2023/04/11 05:56:13 [emerg] 1#1: cannot load certificate "/etc/letsencrypt/live/auctionforfun.site/certificate.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/auctionforfun.site/certificate.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2023/04/11 05:56:27 [emerg] 1#1: cannot load certificate "/etc/letsencrypt/live/auctionforfun.site/certificate.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/auctionforfun.site/certificate.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2023/04/11 05:56:53 [emerg] 1#1: cannot load certificate "/etc/letsencrypt/live/auctionforfun.site/certificate.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/auctionforfun.site/certificate.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2023/04/11 05:57:45 [emerg] 1#1: cannot load certificate "/etc/letsencrypt/live/auctionforfun.site/certificate.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/auctionforfun.site/certificate.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2023/04/11 05:58:46 [emerg] 1#1: cannot load certificate "/etc/letsencrypt/live/auctionforfun.site/certificate.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/auctionforfun.site/certificate.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2023/04/11 06:42:14 [error] 29#29: *14 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "POST /api/v1/auth/google?idToken=eyJhbGciOiJSUzI1NiIsImtpZCI6ImFjZGEzNjBmYjM2Y2QxNWZmODNhZjgzZTE3M2Y0N2ZmYzM2ZDExMWMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2ODExOTUwMzMsImF1ZCI6IjYwNjc0NDgzMDk2LXAwMTRlM2VjYTI2NHZyOHZuNnNxMTRnczEyZzBxYzlnLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTAyOTQ3NzY4OTg5Njc3NDMzNTM4IiwiZW1haWwiOiJ2aG5nZG5nQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhenAiOiI2MDY3NDQ4MzA5Ni1wMDE0ZTNlY2EyNjR2cjh2bjZzcTE0Z3MxMmcwcWM5Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsIm5hbWUiOiJob2FuZyBkdW5nIHZ1IiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FHTm15eGIzWGJyWWdVR3Boblg1M3Utd1paakUyNnd3dk9KSU5mc09UR3JPPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6ImhvYW5nIGR1bmciLCJmYW1pbHlfbmFtZSI6InZ1IiwiaWF0IjoxNjgxMTk1MzMzLCJleHAiOjE2ODExOTg5MzMsImp0aSI6ImJjNzQ5OWU4ZmNiNjhjYjRlODI5ZjVkNTY0MmFhMmMyNzhjYzBjMTEifQ.o34_hOp4Mk-UL1CtH4vAPAN8Lc_uK4Rqbf1D8UknJK5SVDQJS-rc7s2dHs21w_bdlZsrljgXlrI6jxLcK4L_M_VxVFhZy4rrA9JsR1J9edYQ7I2tQI0C4mYaPXLqBdAnLS8lgUiqOiro05QqB0XKnFNZpAkaKMQOe36apMTqfVwqbJ50Vd2zqwJolxjOjWUbf0Ol-U9fJb7Byafkm6aP-m6kWZYt0wrjsox9-yvGwBh4uYa_x-j7BTDtzfLAAVOFWDIPQ4e6kaRkWA15cpeRa8g7a4P-OC-cmJC0jpcHlXJAeNbcZ6KpaoawiWeVc3111c7xB2-U8SZWGdJnPGgQhg HTTP/1.1", upstream: "http://172.20.0.2:8080/api/v1/auth/google?idToken=eyJhbGciOiJSUzI1NiIsImtpZCI6ImFjZGEzNjBmYjM2Y2QxNWZmODNhZjgzZTE3M2Y0N2ZmYzM2ZDExMWMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2ODExOTUwMzMsImF1ZCI6IjYwNjc0NDgzMDk2LXAwMTRlM2VjYTI2NHZyOHZuNnNxMTRnczEyZzBxYzlnLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTAyOTQ3NzY4OTg5Njc3NDMzNTM4IiwiZW1haWwiOiJ2aG5nZG5nQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhenAiOiI2MDY3NDQ4MzA5Ni1wMDE0ZTNlY2EyNjR2cjh2bjZzcTE0Z3MxMmcwcWM5Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsIm5hbWUiOiJob2FuZyBkdW5nIHZ1IiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FHTm15eGIzWGJyWWdVR3Boblg1M3
2023/04/11 06:42:14 [error] 29#29: *14 open() "/etc/nginx/html/50x.html" failed (2: No such file or directory), client: 172.20.0.1, server: , request: "POST /api/v1/auth/google?idToken=eyJhbGciOiJSUzI1NiIsImtpZCI6ImFjZGEzNjBmYjM2Y2QxNWZmODNhZjgzZTE3M2Y0N2ZmYzM2ZDExMWMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2ODExOTUwMzMsImF1ZCI6IjYwNjc0NDgzMDk2LXAwMTRlM2VjYTI2NHZyOHZuNnNxMTRnczEyZzBxYzlnLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTAyOTQ3NzY4OTg5Njc3NDMzNTM4IiwiZW1haWwiOiJ2aG5nZG5nQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhenAiOiI2MDY3NDQ4MzA5Ni1wMDE0ZTNlY2EyNjR2cjh2bjZzcTE0Z3MxMmcwcWM5Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsIm5hbWUiOiJob2FuZyBkdW5nIHZ1IiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FHTm15eGIzWGJyWWdVR3Boblg1M3Utd1paakUyNnd3dk9KSU5mc09UR3JPPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6ImhvYW5nIGR1bmciLCJmYW1pbHlfbmFtZSI6InZ1IiwiaWF0IjoxNjgxMTk1MzMzLCJleHAiOjE2ODExOTg5MzMsImp0aSI6ImJjNzQ5OWU4ZmNiNjhjYjRlODI5ZjVkNTY0MmFhMmMyNzhjYzBjMTEifQ.o34_hOp4Mk-UL1CtH4vAPAN8Lc_uK4Rqbf1D8UknJK5SVDQJS-rc7s2dHs21w_bdlZsrljgXlrI6jxLcK4L_M_VxVFhZy4rrA9JsR1J9edYQ7I2tQI0C4mYaPXLqBdAnLS8lgUiqOiro05QqB0XKnFNZpAkaKMQOe36apMTqfVwqbJ50Vd2zqwJolxjOjWUbf0Ol-U9fJb7Byafkm6aP-m6kWZYt0wrjsox9-yvGwBh4uYa_x-j7BTDtzfLAAVOFWDIPQ4e6kaRkWA15cpeRa8g7a4P-OC-cmJC0jpcHlXJAeNbcZ6KpaoawiWeVc3111c7xB2-U8SZWGdJnPGgQhg HTTP/1.1", upstream: "http://172.20.0.2:8080/api/v1/auth/google?idToken=eyJhbGciOiJSUzI1NiIsImtpZCI6ImFjZGEzNjBmYjM2Y2QxNWZmODNhZjgzZTE3M2Y0N2ZmYzM2ZDExMWMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2ODExOTUwMzMsImF1ZCI6IjYwNjc0NDgzMDk2LXAwMTRlM2VjYTI2NHZyOHZuNnNxMTRnczEyZzBxYzlnLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTAyOTQ3NzY4OTg5Njc3NDMzNTM4IiwiZW1haWwiOiJ2aG5nZG5nQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhenAiOiI2MDY3NDQ4MzA5Ni1wMDE0ZTNlY2EyNjR2cjh2bjZzcTE0Z3MxMmcwcWM5Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsIm5hbWUiOiJob2FuZyBkdW5nIHZ1IiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FHTm15eGIzWGJyWWdVR3Boblg1M3
2023/04/11 06:42:35 [error] 29#29: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "POST /api/v1/auth/login HTTP/1.1", upstream: "http://172.20.0.2:8080/api/v1/auth/login", host: "localhost:8081", referrer: "http://localhost:8081/login"
2023/04/11 06:42:35 [error] 29#29: *16 open() "/etc/nginx/html/50x.html" failed (2: No such file or directory), client: 172.20.0.1, server: , request: "POST /api/v1/auth/login HTTP/1.1", upstream: "http://172.20.0.2:8080/api/v1/auth/login", host: "localhost:8081", referrer: "http://localhost:8081/login"
2023/04/11 06:42:36 [error] 29#29: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "POST /api/v1/auth/login HTTP/1.1", upstream: "http://172.20.0.2:8080/api/v1/auth/login", host: "localhost:8081", referrer: "http://localhost:8081/login"
2023/04/11 06:42:36 [error] 29#29: *16 open() "/etc/nginx/html/50x.html" failed (2: No such file or directory), client: 172.20.0.1, server: , request: "POST /api/v1/auth/login HTTP/1.1", upstream: "http://172.20.0.2:8080/api/v1/auth/login", host: "localhost:8081", referrer: "http://localhost:8081/login"
